version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3333/api
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"