version: '3.8'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/family-tree-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.family-tree.rule=Host(`mesoriginesdefamille.alng.fr`)"
      - "traefik.http.routers.family-tree.entrypoints=websecure"
      - "traefik.http.routers.family-tree.tls=true"
      - "traefik.http.routers.family-tree.tls.certresolver=myresolver"
      - "traefik.http.services.family-tree.loadbalancer.server.port=80"
    depends_on:
      - familytreeapi
    environment:
      - API_URL=http://mesoriginesdefamille.alng.fr/api
    networks:
      - traefik
      - familytreenet

  familytreeapi:
    image: ${DOCKERHUB_USERNAME}/family-tree-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.family-tree.rule=Host(`mesoriginesdefamille.alng.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.family-tree.entrypoints=websecure"
      - "traefik.http.routers.family-tree.tls=true"
      - "traefik.http.routers.family-tree.tls.certresolver=myresolver"
      - "traefik.http.services.family-tree.loadbalancer.server.port=3333"
    # depends_on:
    #   - redis
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - traefik
      - familytreenet

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - familytreenet
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 -p 6379 ping | grep PONG"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 5
  #     start_period: 5s

networks:
  traefik:
    name: traefik
    external: true
  familytreenet:
    name: familytreenet