version: '3.8'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/family-tree-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.family-tree.rule=Host(`mesoriginesdefamille.alng.fr`)"
      - "traefik.http.routers.family-tree.entrypoints=websecure" # Utilise HTTPS
      - "traefik.http.routers.family-tree.tls=true" # Active TLS
      - "traefik.http.routers.family-tree.tls.certresolver=myresolver" # Utilise le resolver Let's Encrypt
      - "traefik.http.services.family-tree.loadbalancer.server.port=80" # Port interne de WordPress
    # ports:
    #   - '80:80'
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3333/api
    networks:
      - traefik

  backend:
    image: ${DOCKERHUB_USERNAME}/family-tree-backend:latest
    ports:
      - '3333:3333'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379
    networks:
      - traefik

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

networks:
  traefik:
    name: traefik
    external: true