version: '3.8'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/family-tree-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.family-tree.rule=Host(`mesoriginesdefamille.alng.fr`)"
      - "traefik.http.routers.family-tree.entrypoints=websecure" # Utilise HTTPS
      - "traefik.http.routers.family-tree.tls=true" # Active TLS
      - "traefik.http.routers.family-tree.tls.certresolver=myresolver" # Utilise le resolver Let's Encrypt
      - "traefik.http.services.family-tree.loadbalancer.server.port=80" # Port interne de WordPress
    # ports:
    #   - '80:80'
    depends_on:
      - familytreeapi
    environment:
      - API_URL=https://mesoriginesdefamille.alng.fr/api
    networks:
      - traefik
      - familytreenet

  familytreeapi:
    image: ${DOCKERHUB_USERNAME}/family-tree-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.family-tree-api.rule=Host(`mesoriginesdefamille.alng.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.family-tree-api.entrypoints=websecure" # Utilise HTTPS
      - "traefik.http.routers.family-tree-api.tls=true" # Active TLS
      - "traefik.http.routers.family-tree-api.tls.certresolver=myresolver" # Utilise le resolver Let's Encrypt
      - "traefik.http.services.family-tree-api.loadbalancer.server.port=3333" # Port interne de WordPress
    # ports:
    #   - '3333:3333'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - familytreenet

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - familytreenet

  alpine-terminal:
    image: alpine:latest
    container_name: alpine-terminal
    command: /bin/sh
    stdin_open: true
    tty: true
    networks:
      - familytreenet

networks:
  traefik:
    name: traefik
    external: true
  familytreenet:
    name: familytreenet